/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_edd;

import java.awt.event.KeyEvent;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.*;

import javax.swing.table.DefaultTableModel;

public class CrearPlantas extends javax.swing.JFrame {

    /**
     * Creates new form CrearPersonaje
     */
   public static ListaDoble lista=new ListaDoble();
   
   JFileChooser elegir;
   File guardar;
   ArrayList <String> Img=new ArrayList();
   public static ArrayList <String> NombresPanel=new ArrayList();
   public static ArrayList<String>imagenes=new ArrayList();
   int contador=0;
   
   
    public CrearPlantas() {
        initComponents();
              
        Img.add("planta1.png");
        Img.add("planta2.png");
        Img.add("planta3.png");
        Img.add("planta4.png");
    }
    public void MostrarImagenes(String img)
    {
         String path="/imagenes/"+img;
          URL url=this.getClass().getResource(path);
          ImageIcon icon=new ImageIcon(url);
          imagen.setIcon(icon);
    }
    public void MostrarImagenes2(String img)
    {
         String path="/imagenes/"+img;
          URL url=this.getClass().getResource(path);
          ImageIcon icon=new ImageIcon(url);
          result.setIcon(icon);
    }
    public void MostrarImagenesAgregadas(String path)
    {
          URL url=this.getClass().getResource(path);
          ImageIcon icon=new ImageIcon(url);
          imagen.setIcon(icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        ataque = new javax.swing.JTextField();
        defensa = new javax.swing.JTextField();
        insertar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        adelante = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Imag = new javax.swing.JLabel();
        result = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox();
        AgregarImagenes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creando Plantas");
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 200, -1));

        ataque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ataqueKeyTyped(evt);
            }
        });
        getContentPane().add(ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));

        defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defensaActionPerformed(evt);
            }
        });
        defensa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                defensaKeyTyped(evt);
            }
        });
        getContentPane().add(defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, -1));

        insertar.setBackground(new java.awt.Color(51, 51, 51));
        insertar.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        insertar.setForeground(new java.awt.Color(255, 255, 255));
        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        getContentPane().add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        modificar.setBackground(new java.awt.Color(51, 51, 51));
        modificar.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        eliminar.setBackground(new java.awt.Color(51, 51, 51));
        eliminar.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        atras.setBackground(new java.awt.Color(51, 51, 51));
        atras.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        adelante.setBackground(new java.awt.Color(51, 51, 51));
        adelante.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        adelante.setForeground(new java.awt.Color(255, 255, 255));
        adelante.setText(">");
        adelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelanteActionPerformed(evt);
            }
        });
        getContentPane().add(adelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntos Ataque", "Puntos Defensa", "Tipo Disparo", "Imagen"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 520, 130));
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 120, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Nombre:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Puntos de Ataque:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Puntos de Defensa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Tipo de Disparo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        Imag.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Imag.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(Imag, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 130, 110));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, -1, -1));

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Directo", "Disparo" }));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, -1));

        AgregarImagenes.setBackground(new java.awt.Color(51, 51, 51));
        AgregarImagenes.setFont(new java.awt.Font("Ravie", 1, 12)); // NOI18N
        AgregarImagenes.setForeground(new java.awt.Color(255, 255, 255));
        AgregarImagenes.setText("AgregarImagenes");
        AgregarImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarImagenesActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarImagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
       
        try{
         String nom=nombre.getText().trim();
         String ata=ataque.getText().trim();
         String def=defensa.getText().trim();
         String tip=tipo.getSelectedItem().toString();
         
         if(!nom.isEmpty()&&!ata.isEmpty()&&!def.isEmpty()&&!tip.isEmpty())
            lista.editar(nom,Integer.valueOf(ata), Integer.valueOf(def), tip);
         if(!ata.isEmpty()){
            lista.editar(nom,Integer.valueOf(ata),-1, tip);     
         }
         if(!def.isEmpty()){
            lista.editar(nom,-1,Integer.valueOf(def), tip);     
         }
         if(!tip.isEmpty())
         {
            lista.editar(nom,-1,-1, tip);         
         }
         
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
              for (int i = 0; i < ListaDoble.size; i++) {
                  for(int j=0;j<4;j++){
                      //System.out.println(jTable1.getValueAt(i, j));
                  if(jTable1.getValueAt(i, j).equals(nom)){  
                      jTable1.setValueAt(nom, i, j);
                      if(!ata.isEmpty())
                      jTable1.setValueAt(ata, i, j+1);
                      if(!def.isEmpty())
                      jTable1.setValueAt(def, i, j+2);
                      if(!tip.isEmpty())
                      jTable1.setValueAt(tip, i, j+3);
                  }  
               }
              }
        }catch(Exception ex){
        //    System.out.println(ex);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        try{
        String nom=nombre.getText().trim();
        int  ataq=Integer.valueOf(ataque.getText().trim());
        int  def=Integer.valueOf(defensa.getText().trim());
        String tip=tipo.getSelectedItem().toString();
        String img=Imag.getText();
        
        if(!img.isEmpty()){
        Personajes objeto=new Personajes(nom,ataq,def,tip,img);
        lista.insertarCabezaLista(objeto);
        lista.visualizar();
        jTable1.getTableHeader().setReorderingAllowed(false) ;

        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
        Object [] filas=new Object[modelo.getColumnCount()];
             
        filas[0]=nom;
        filas[1]=ataq;
        filas[2]=def;
        filas[3]=tip;
        filas[4]=Imag.getText();
        combo.addItem(nom);
        modelo.addRow(filas);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una imagen");
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"LLenar Campos");

        }
    }//GEN-LAST:event_insertarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
             
        try{
         String nom=nombre.getText().trim();  
         lista.eliminar(nom);
         combo.removeItem(nom);
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
              for (int i = 0; i < ListaDoble.size; i++) {
                  for(int j=0;j<4;j++){
                      //System.out.println(jTable1.getValueAt(i, j));
                  if(jTable1.getValueAt(i, j).equals(nom))    
                   modelo.removeRow(i);
                //  System.out.println(ListaDoble.size);
                  }
              }
        }catch(Exception ex){
        //    System.out.println(ex);
        }
      //  jTable1.setModel(new DefaultTableModel());
    }//GEN-LAST:event_eliminarActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
     
        try{
           contador--;
        if(contador<Img.size()&&contador>=0){
           System.out.println(Img.get(contador));
           Imag.setText(Img.get(contador));
           MostrarImagenes(Img.get(contador));
        }if(contador<=0){
            contador=0;
        }
        System.out.println("contador: "+contador);

        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_atrasActionPerformed

    private void adelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelanteActionPerformed
        try{
        if(contador<Img.size()){
           System.out.println(Img.get(contador));
           Imag.setText(Img.get(contador));
           MostrarImagenes(Img.get(contador));
            contador++;
        }else if(contador==Img.size()){
            contador=Img.size();
        }
          
            System.out.println("contador: "+contador);
        }catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_adelanteActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
       // System.out.println(combo.getSelectedItem().toString());
       for(int i=0;i<jTable1.getRowCount();i++){
           if(jTable1.getValueAt(i,0).equals(combo.getSelectedItem().toString())){
               System.out.println(jTable1.getValueAt(i,0));
               MostrarImagenes2(jTable1.getValueAt(i, 4).toString());
           }
       }
    }//GEN-LAST:event_comboActionPerformed

    private void defensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defensaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
          for(int i=0;i<jTable1.getRowCount();i++){
             imagenes.add(jTable1.getValueAt(i, 4).toString());
             NombresPanel.add(jTable1.getValueAt(i, 0).toString());
          }
        CrearZombies ventana=new CrearZombies();
         ventana.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ataqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ataqueKeyTyped
        validarNumeros(evt,ataque);
    }//GEN-LAST:event_ataqueKeyTyped

    private void defensaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_defensaKeyTyped
        validarNumeros(evt,defensa);
    }//GEN-LAST:event_defensaKeyTyped

    private void AgregarImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarImagenesActionPerformed
        elegir=new JFileChooser();
        int respuesta=elegir.showOpenDialog(this);
        
        if(respuesta==JFileChooser.APPROVE_OPTION){
            File ArchivoElegido=elegir.getSelectedFile();
            Img.add(ArchivoElegido.getName());
            System.out.println(ArchivoElegido.getName());
        }
        
        
    }//GEN-LAST:event_AgregarImagenesActionPerformed
    public void validarNumeros(KeyEvent evt,JTextField cantidad){
          char tecla;
        tecla=evt.getKeyChar();
        if(!Character.isDigit(tecla)&&tecla!=KeyEvent.VK_BACK_SPACE){
           evt.consume();
           getToolkit().beep();
        }
        if(tecla=='.'&&cantidad.getText().contains(".")){
            evt.consume();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPlantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarImagenes;
    private javax.swing.JLabel Imag;
    private javax.swing.JButton adelante;
    private javax.swing.JTextField ataque;
    private javax.swing.JButton atras;
    private javax.swing.JComboBox combo;
    private javax.swing.JTextField defensa;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton insertar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel result;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables
}
