/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_edd;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KRATOS
 */
public class CrearPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form CrearPersonaje
     */
   public static ListaDoble lista=new ListaDoble();
    public CrearPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        ataque = new javax.swing.JTextField();
        defensa = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        insertar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setText("jTextField1");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 200, -1));

        ataque.setText("jTextField2");
        getContentPane().add(ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 200, -1));

        defensa.setText("jTextField3");
        getContentPane().add(defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, -1));

        tipo.setText("jTextField4");
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, -1));

        insertar.setBackground(new java.awt.Color(51, 51, 51));
        insertar.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        insertar.setForeground(new java.awt.Color(255, 255, 255));
        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        getContentPane().add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        modificar.setBackground(new java.awt.Color(51, 51, 51));
        modificar.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        eliminar.setBackground(new java.awt.Color(51, 51, 51));
        eliminar.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(">");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntos Ataque", "Puntos Defensa", "Tipo Disparo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 520, 130));

        imagen.setText("jLabel6");
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 110, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Nombre:");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Puntos de Ataque:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Puntos de Defensa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Tipo de Disparo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        /*String path="/imagenes/zombies.jpg";
        URL url=this.getClass().getResource(path);
        ImageIcon icon=new ImageIcon(url);
        imagen.setIcon(icon);*/
        try{
         String nom=nombre.getText().trim();
         String ata=ataque.getText().trim();
         String def=defensa.getText().trim();
         String tip=tipo.getText().trim();
         
         if(!nom.isEmpty()&&!ata.isEmpty()&&!def.isEmpty()&&!tip.isEmpty())
            lista.editar(nom,Integer.valueOf(ata), Integer.valueOf(def), tip);
         if(!ata.isEmpty()){
            lista.editar(nom,Integer.valueOf(ata),-1, tip);     
         }
         if(!def.isEmpty()){
            lista.editar(nom,-1,Integer.valueOf(def), tip);     
         }
         if(!tip.isEmpty())
         {
            lista.editar(nom,-1,-1, tip);         
         }
         
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
              for (int i = 0; i < ListaDoble.size; i++) {
                  for(int j=0;j<4;j++){
                      //System.out.println(jTable1.getValueAt(i, j));
                  if(jTable1.getValueAt(i, j).equals(nom)){  
                      jTable1.setValueAt(nom, i, j);
                      if(!ata.isEmpty())
                      jTable1.setValueAt(ata, i, j+1);
                      if(!def.isEmpty())
                      jTable1.setValueAt(def, i, j+2);
                      if(!tip.isEmpty())
                      jTable1.setValueAt(tip, i, j+3);
                  }  
               }
              }
        }catch(Exception ex){
        //    System.out.println(ex);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        String nom=nombre.getText().trim();
        int  ataq=Integer.valueOf(ataque.getText().trim());
        int  def=Integer.valueOf(defensa.getText().trim());
        String tip=tipo.getText().trim();

        Personajes objeto=new Personajes(nom,ataq,def,tip);
        lista.insertarCabezaLista(objeto);
        lista.visualizar();
        jTable1.getTableHeader().setReorderingAllowed(false) ;

        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
        // Estudiante op[]=new Estudiante[Listado.ListEstudiantes.size()];
        Object [] filas=new Object[modelo.getColumnCount()];
        // String path="/imagenes/plantas.jpg";
        //URL url=this.getClass().getResource(path);dffffsdfd
        //ImageIcon icon=new ImageIcon(url);
        //  imagen.setIcon(icon);
      
        filas[0]=nom;
        filas[1]=ataq;
        filas[2]=def;
        filas[3]=tip;
        modelo.addRow(filas);

    }//GEN-LAST:event_insertarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
             
        try{
         String nom=nombre.getText().trim();  
         lista.eliminar(nom);
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
              for (int i = 0; i < ListaDoble.size; i++) {
                  for(int j=0;j<4;j++){
                      //System.out.println(jTable1.getValueAt(i, j));
                  if(jTable1.getValueAt(i, j).equals(nom))    
                   modelo.removeRow(i);
                //  System.out.println(ListaDoble.size);
                  }
              }
        }catch(Exception ex){
        //    System.out.println(ex);
        }
      //  jTable1.setModel(new DefaultTableModel());
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ataque;
    private javax.swing.JTextField defensa;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton insertar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
