/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_edd;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author KRATOS
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static ListaEnlazada ListaInformacion=new ListaEnlazada();
    public static ListaEnlazada ListaPilaZombies=new ListaEnlazada();
    public static ListaEnlazada ListaColaPlantas=new ListaEnlazada();
    public Inicio() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Plantas = new javax.swing.JButton();
        Zombis = new javax.swing.JButton();
        Juego = new javax.swing.JButton();
        Eliminar_Juego = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        reportes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JUGADORES");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Plantas.setBackground(new java.awt.Color(51, 51, 51));
        Plantas.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        Plantas.setForeground(new java.awt.Color(255, 255, 255));
        Plantas.setText("JUGADOR PLANTAS");
        Plantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantasActionPerformed(evt);
            }
        });
        getContentPane().add(Plantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        Zombis.setBackground(new java.awt.Color(51, 51, 51));
        Zombis.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        Zombis.setForeground(new java.awt.Color(255, 255, 255));
        Zombis.setText("JUGADOR ZOMBIS");
        Zombis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZombisActionPerformed(evt);
            }
        });
        getContentPane().add(Zombis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        Juego.setBackground(new java.awt.Color(51, 51, 51));
        Juego.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        Juego.setForeground(new java.awt.Color(255, 255, 255));
        Juego.setText("COMENZAR JUEGO");
        Juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegoActionPerformed(evt);
            }
        });
        getContentPane().add(Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        Eliminar_Juego.setBackground(new java.awt.Color(51, 51, 51));
        Eliminar_Juego.setFont(new java.awt.Font("Ravie", 1, 18)); // NOI18N
        Eliminar_Juego.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar_Juego.setText("ELIMINAR DATOS");
        Eliminar_Juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_JuegoActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar_Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jugadores.png", "CatalogoPlanta.png", "CatalagoZombie.png", "Pila.png", "Cola.png", "prueba.png" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, -1));

        reportes.setBackground(new java.awt.Color(0, 0, 0));
        reportes.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setText("Generar Reportes");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        getContentPane().add(reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/portada.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantasActionPerformed
        Plantas ventana=new Plantas();
        ventana.setVisible(true);
    }//GEN-LAST:event_PlantasActionPerformed

    private void ZombisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZombisActionPerformed
        Zombies ventana=new Zombies();
        ventana.setVisible(true);
    }//GEN-LAST:event_ZombisActionPerformed

    private void JuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegoActionPerformed
         
        if(!ListaInformacion.isEmpty())
        {
           Tablero ventana=new Tablero();
           ventana.setVisible(true);
           // this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "No se ha creado Los Usuarios");
        }
    }//GEN-LAST:event_JuegoActionPerformed

    private void Eliminar_JuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_JuegoActionPerformed
      
        ListaInformacion.VaciarLista();
        ListaInformacion.iniciarVariables();
        
        CrearPlantas.lista.VaciarLista();
        CrearPlantas.lista.inicializarVariables();
        
        CrearZombies.lista2.VaciarLista();
        CrearZombies.lista2.inicializarVariables();
        
        ListaPilaZombies.VaciarLista();
        ListaPilaZombies.iniciarVariables();
        
        ListaColaPlantas.VaciarLista();
        ListaColaPlantas.iniciarVariables();
        
        Hilo.iniciarVariables();
    }//GEN-LAST:event_Eliminar_JuegoActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        
        String seleccionado=(String)combo.getSelectedItem();
            try {
                File path = new File (seleccionado);
                if(path.exists()){
                 Desktop.getDesktop().open(path);
                }else{
                  JOptionPane.showMessageDialog(this, "No existe el Archivo");
                }
                }catch (IOException ex) {
                ex.printStackTrace();
           }
    }//GEN-LAST:event_comboActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
       
        if(!ListaInformacion.isEmpty()){
        ListaInformacion.imprimir();
        }else{
            JOptionPane.showMessageDialog(null,"Lista Jugadores vacia");
        }
        if(!ListaColaPlantas.isEmpty())
        {
            ListaColaPlantas.imprimirCola();
        }else{
            JOptionPane.showMessageDialog(null,"Lista Personajes Plantas(Cola) vacia");
        }
        if(!ListaPilaZombies.isEmpty())
        {
            ListaPilaZombies.imprimirPila();
        }else{
            JOptionPane.showMessageDialog(null,"Lista Personajes Zombies(Pila) vacia");
        }
        if(!CrearZombies.lista2.isEmpty())
        {
            CrearZombies.lista2.imprimir2();
        }
        else{
            JOptionPane.showMessageDialog(null,"Lista Catalogo Zombies vacia");
        }
        if(!CrearPlantas.lista.isEmpty())
        {
            CrearPlantas.lista.imprimir();
        }else{
            JOptionPane.showMessageDialog(null,"Lista Catalogo Plantas vacia");
        }
    }//GEN-LAST:event_reportesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        System.out.println("Freddy-201212854");
        
       /* ListaEnlazada list=new ListaEnlazada();
        list.InsertAtFront("3");
        list.InsertAtFront("2");
        list.InsertAtFront("1");
        list.InsertAtFront("0");
        list.imprimir();*/
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar_Juego;
    private javax.swing.JButton Juego;
    private javax.swing.JButton Plantas;
    private javax.swing.JButton Zombis;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reportes;
    // End of variables declaration//GEN-END:variables
}
