/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_edd;

import java.awt.*;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author KRATOS
 */
public class Tablero extends javax.swing.JFrame {
   JLabel lab,lab2;
   static JPanel panel,panel2;
    int contador=100;
    public Tablero() {
        initComponents();
        
          Hilo.empezarHilo();
          String path="/imagenes/planta1.png";
          URL url=this.getClass().getResource(path);
          ImageIcon icon=new ImageIcon(url);
          
              lab=new JLabel("fds");
              lab.setBounds(500,100,100,100);
              lab.setIcon(icon);
              add(lab);
         
                JPanel gui = new JPanel(new BorderLayout(3,3));
                gui.setBounds(50,70,200,600);
                panel = new JPanel(new GridLayout(0,1));
                JScrollPane scroll = new JScrollPane(panel);
                scroll.setPreferredSize(new Dimension(100,100));
                gui.add(scroll, BorderLayout.CENTER);
                JLabel addLabel = new JLabel("Add Label");
                gui.add(addLabel, BorderLayout.NORTH);
                add(gui);
                
                //HiloZombie.empezarHilo2();

                JPanel gui2 = new JPanel(new BorderLayout(3,3));
                gui2.setBounds(1085,70,200,600);
                panel2 = new JPanel(new GridLayout(0,1));
                JScrollPane scroll2 = new JScrollPane(panel2);
                scroll2.setPreferredSize(new Dimension(100,100));
                gui2.add(scroll2, BorderLayout.CENTER);
                JLabel addLabel2 = new JLabel("Add Label");
                gui2.add(addLabel2, BorderLayout.NORTH);
                  
                add(gui2);
                
  
    }
    public static void p(URL url)
    {
      JLabel l=new JLabel();
      l.setBounds(10, 10,100, 100);
      MostrarImagenes(l,url);
      panel.add(l);
      panel.revalidate();
      int height = (int)panel.getPreferredSize().getHeight();
      Rectangle rect = new Rectangle(0,height,10,10);
      panel.scrollRectToVisible(rect); 
    }
     public static void MostrarImagenes(JLabel imagen,URL url)
    {
         
          ImageIcon icon=new ImageIcon(url);
          imagen.setIcon(icon);
    }
     
     public static void pZombie(URL url)
    {
      JLabel l2=new JLabel();
      l2.setBounds(10, 10,100, 100);
      MostrarImagenesZombie(l2,url);
      panel2.add(l2);
      panel2.revalidate();
      int height = (int)panel2.getPreferredSize().getHeight();
      Rectangle rect = new Rectangle(0,height,10,10);
      panel2.scrollRectToVisible(rect); 
    }
     public static void MostrarImagenesZombie(JLabel imagen,URL url)
    {
         
          ImageIcon icon=new ImageIcon(url);
          imagen.setIcon(icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1028, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
